name: Deploy Web

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install build-essential clang libsdl2-dev

      - name: Install emscripten
        run: sudo apt install emscripten

      - name: Compile to WebAssembly
        run: make build-web
      
      - name: Check files
        run: tree
